# DeepSpeed 训练配置文件示例
# 使用 DeepSpeed 进行分布式训练

output_dir = "./runs"
task = "DeepSpeed_Training"
entity = "Lab"
run_id = "" # 由程序随机设置
device = "cuda"
seed = 42
classes = ["class_0", "class_1", "class_2"]
metrics = ['accuracy', 'precision', 'recall', 'f1']
postprocess = "classification"

# 模型配置
[model]
name = "resnet18"
continue_checkpoint = ""
continue_ext_checkpoint = ""
pretrained = ""

[model.config]
n_channels = 3
n_classes = 3
input_sizes = [[1, 3, 224, 224]]
dtypes = ["float32"]

# 损失函数配置
[[criterion]]
type = 'cross_entropy'
weight = 1.0
config = {}

# 数据变换配置
[transform]
RESIZE = [224, 224]
HFLIP = [0.5]
ROTATION = [10]
PIL_TO_TENSOR = []
CONVERT_IMAGE_DTYPE = ['float32']

# 数据集配置
[dataset]
name = "CIFAR10"
base_dir = "./data/cifar10"
config = {download = true}

# 数据加载器配置
[dataloader]
num_workers = 4
shuffle = true
pin_memory = true
drop_last = true

# 训练配置
[train]
batch_size = 32
epoch = 10
save_period = 2
save_recovery_period = 1
grad_accumulation_steps = 1

[train.optimizer]
type = "AdamW"
learning_rate = 0.001
weight_decay = 0.01
betas = [0.9, 0.999]

[train.lr_scheduler]
type = "cosine_annealing"
T_max = 10
eta_min = 0.0001

[train.early_stopping]
patience = 5

# 验证配置
[valid]
batch_size = 64
period = 1
save_best = true

# 测试配置
[test]
batch_size = 64

# DeepSpeed 配置
[deepspeed]
enabled = true
zero_stage = 2
cpu_offload = false
fp16 = true
bf16 = false
log_level = "INFO"
config = "configs/deepspeed/deepspeed_zero2.json"  # 可选：指定配置文件

# 私有配置
[private]
mode = 1

[private.log]
verbose = true
debug = false
