output_dir = "./output"
task = "Test"
entity = "Lab"
run_id = "" # be Random set by program
device = "cuda"
seed = -1
classes = ["Retina"]
metrics = ['iou', 'accuracy', 'precision', 'recall', 'f1', 'dice']

[model]
name = "unet"
continue_checkpoint = ""
continue_ext_checkpoint = ""

[model.config]
n_channels = 1
n_classes = 1

[transform]
# (RESIZE, resize)
# (ROTATION, degree)
# (HFLIP, p)
# (VFLOP, p)
# (INVERT, p)
# (TO_TENSOR)
# (PIL_TO_TENSOR)
# (NORMALIZE, is_rgb)
RESIZE=[512, 512]
# ROTATION=[10]
# HFLIP=[0.1]
# VFLIP=[0.1]
# INVERT=[0.1]
PIL_TO_TENSOR=[]
CONVERT_IMAGE_DTYPE=['float32']
# TO_TENSOR=[]

[[datasets]]
name = "DRIVE"
base_dir = "./data/DRIVE"
betweens = {train = [0.0, 1.0], valid = [0.0, 1.0], test = [0.0, 1.0]}
config = {}

# [[datasets]]
# name = "STARE"
# base_dir = "./data/STARE"
# betweens = {train = [0.0, 1.0], valid = [0.0, 1.0], test = [0.0, 1.0]}

# [[datasets]]
# name = "CHASEDB1"
# base_dir = "./data/CHASEDB1"
# betweens = {train = [0.0, 1.0], valid = [0.0, 1.0], test = [0.0, 1.0]}

[dataloader]
num_workers = 4
shuffle = true

[train]
batch_size = 1
epoch = 40
save_every_n_epoch = 40
grad_accumulation_steps = 0 # <= 0 for disabled
optimizer_type = 'adam' # sgd, adam, adamw

[train.optimizer]
learning_rate = 3e-6
weight_decay = 1e-8
eps = 1e-8

# [train.lr_scheduler]
# warmup = 50
# warmup_lr = 0.03

# [train.scaler]
# compute_type = 'float16'

# [train.early_stopping]
# patience = 3

[valid]
batch_size = 1

[test]
batch_size = 1

[predict]
input = "data/DRIVE/test/images"

[predict.config]

[private]
wandb = false
mode = 0

[private.log]
verbose = false # info mode
debug = false # debug mode
log_file_format = '%Y-%m-%d %H_%M_%S'
log_format = '%(asctime)s %(levelname)s | %(name)s | %(message)s'
