output_dir = "./output"
task = "Test"
entity = "Lab"
run_id = "" # be Random set by program  
device = "cuda"
seed = 42
classes = ["Retina"]
metrics = ['iou', 'accuracy', 'precision', 'recall', 'f1', 'dice']

[model]
name = "test-net"
continue_checkpoint = ""
continue_ext_checkpoint = ""

[model.config]
n_channels = 1
n_classes = 1

[transform]
# (RESIZE, resize)
# (ROTATION, degree)
# (HFLIP, p)
# (VFLOP, p)
# (INVERT, p)
# (TO_TENSOR)
# (PIL_TO_TENSOR)
# (CONVERT_IMAGE_DTYPE, uint8|float32|float64)
# (NORMALIZE, is_rgb)
RESIZE=[512, 512]
# ROTATION=[10]
# HFLIP=[0.1]
# VFLIP=[0.1]
# INVERT=[0.1]
PIL_TO_TENSOR=[]
# TO_TENSOR=[]
CONVERT_IMAGE_DTYPE=['float32']
# NORMALIZE=[False]

[dataset]
name = "DRIVE"
path = "./data/DRIVE"
num_workers = 4

[train]
batch_size = 1
epoch = 40
save_every_n_epoch = 10
grad_accumulation_steps = 0 # <= 0 for disabled

[train.optimizer]
learning_rate = 3e-6
weight_decay = 1e-8
eps = 1e-8
type = 'adamw' # adam, adamw

[train.lr_scheduler]
enabled = false
warmup = 50
warmup_lr = 0.03

[train.scaler]
enabled = false
compute_type = 'bfloat16'

[train.early_stopping]
enabled = false
patience = 3

[valid]
batch_size = 1

[test]
batch_size = 1

[predict]
input = "data/DRIVE/test/images"

[predict.config]

[private]
wandb = false
mode = 0

[private.log]
verbose = false # info mode
debug = false # debug mode
log_file_format = '%Y-%m-%d %H_%M_%S'
log_format = '%(asctime)s %(levelname)s | %(name)s | %(message)s'
