[drive]
config = "configs/single/train-drive.toml"
ext_args = ["--train", "--test", "--predict"]

[stare]
config = "configs/single/train-stare.toml"
ext_args = ["--train", "--test", "--predict"]

[chasedb1]
config = "configs/single/train-chasedb1.toml"
ext_args = ["--train", "--test", "--predict"]
