[dataset]
name = "DRIVE"
base_dir = "./data/DRIVE"
save_dir = "./data/cache"
betweens = {"train" = [0.0, 1.0], "valid" = [0.0, 1.0], "test" = [0.0, 1.0]}


[transform]
# (RESIZE, resize)
# (ROTATION, degree)
# (HFLIP, p)
# (VFLOP, p)
# (INVERT, p)
# (TO_TENSOR)
# (PIL_TO_TENSOR)
# (CONVERT_IMAGE_DTYPE, uint8|float32|float64)
# (NORMALIZE, is_rgb)
RESIZE=[512, 512]
# ROTATION=[10]
# HFLIP=[0.1]
# VFLIP=[0.1]
# INVERT=[0.1]
PIL_TO_TENSOR=[]
# TO_TENSOR=[]
CONVERT_IMAGE_DTYPE=['float32']
# NORMALIZE=[False]

[config]
