# BraTS2020 Brain Tumor Segmentation Dataset Configuration

dataset:
  name: "BraTS2020"
  type: "BraTS2020Dataset"
  
  # Dataset paths
  data_root: "/media/rczx/Data/data/BraTS2020"
  
  # Dataset splits
  splits:
    train:
      split: "train"
      load_seg: true
      num_samples: 371
    val:
      split: "val" 
      load_seg: false
      num_samples: 125
  
  # MRI modalities to load
  modalities:
    - "t1"      # T1-weighted
    - "t1ce"    # T1-weighted with contrast enhancement
    - "t2"      # T2-weighted  
    - "flair"   # Fluid Attenuated Inversion Recovery
  
  # Preprocessing options
  preprocessing:
    normalize: true           # Normalize intensity to [0,1]
    cache_data: false        # Cache loaded data in memory
    
  # Tumor segmentation classes
  classes:
    background: 0            # Background
    necrotic_core: 1        # NCR - Necrotic and Non-Enhancing Tumor Core
    peritumoral_edema: 2    # ED - Peritumoral Edema
    enhancing_tumor: 4      # ET - GD-Enhancing Tumor
  
  # Data properties
  properties:
    image_size: [240, 240, 155]  # Standard BraTS image dimensions (H, W, D)
    voxel_spacing: [1.0, 1.0, 1.0]  # mm
    num_modalities: 4
    
# DataLoader configuration
dataloader:
  batch_size: 1            # Typically 1 for 3D medical images
  num_workers: 4           # Number of data loading workers
  pin_memory: true         # Pin memory for faster GPU transfer
  shuffle:
    train: true
    val: false
  drop_last:
    train: false
    val: false

# Data augmentation (optional transforms)
augmentation:
  enabled: false
  
  # Spatial transforms
  spatial:
    random_flip:
      enabled: false
      axes: [0, 1, 2]       # Flip along H, W, D axes
      prob: 0.5
    
    random_rotation:
      enabled: false
      degrees: 10           # Max rotation degrees
      prob: 0.3
    
    random_crop:
      enabled: false
      size: [224, 224, 144] # Crop size
      prob: 0.5
  
  # Intensity transforms  
  intensity:
    random_noise:
      enabled: false
      std: 0.1              # Gaussian noise std
      prob: 0.3
    
    random_gamma:
      enabled: false
      gamma_range: [0.8, 1.2]
      prob: 0.3
    
    random_bias_field:
      enabled: false
      coefficients: 0.5
      prob: 0.3

# Validation and testing
validation:
  metrics:
    - "dice_coefficient"    # Dice coefficient for segmentation
    - "hausdorff_distance" # Hausdorff distance
    - "surface_dice"       # Surface Dice
  
  # Evaluation regions
  regions:
    whole_tumor: [1, 2, 4]     # All tumor classes
    tumor_core: [1, 4]         # Necrotic core + enhancing tumor  
    enhancing_tumor: [4]       # Only enhancing tumor

# Model training specific settings
training:
  # Loss function weights for imbalanced classes
  class_weights:
    auto: true              # Automatically calculate from data
    manual: null            # Or specify manual weights [w0, w1, w2, w4]
  
  # Multi-scale training
  multi_scale:
    enabled: false
    scales: [0.8, 1.0, 1.2]
  
  # Mixed precision training
  mixed_precision:
    enabled: true
    dtype: "bfloat16"       # Use bfloat16 as specified in project rules

# Dataset statistics (for reference)
statistics:
  train_samples: 371
  val_samples: 125
  total_samples: 496
  
  # Approximate dataset size
  storage:
    train_size_gb: ~65      # Approximate training data size
    val_size_gb: ~22        # Approximate validation data size
    total_size_gb: ~87      # Total dataset size
  
  # Data distribution (approximate)
  tumor_distribution:
    glioblastoma: ~60%      # High-grade gliomas
    lower_grade: ~40%       # Lower-grade gliomas