# CIFAR-10图像分类配置文件

# 实验基本信息
name: cifar10_classification
description: CIFAR-10 image classification training

# 数据集配置
dataset:
  name: cifar10
  root_dir: data/cifar10
  config:
    download: true
    valid_ratio: 0.1  # 从训练集中划分10%作为验证集

# 数据加载配置
dataloader:
  batch_size: 128
  num_workers: 4
  pin_memory: true
  shuffle: true
  drop_last: false

# 模型配置
model:
  name: resnet18  # 或其他分类模型
  num_classes: 10
  pretrained: false

# 训练配置
training:
  epochs: 200
  learning_rate: 0.1
  optimizer: sgd
  momentum: 0.9
  weight_decay: 0.0005
  scheduler: cosine
  warmup_epochs: 5
  
  # 损失函数
  loss: cross_entropy
  
  # 梯度裁剪
  grad_clip: 1.0
  
  # 混合精度训练
  use_amp: true

# 验证配置
validation:
  interval: 1  # 每个epoch验证一次
  metrics:
    - accuracy
    - top1_accuracy
    - precision
    - recall
    - f1_score

# 优化器配置
optimizer:
  type: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: true

# 学习率调度器配置
scheduler:
  type: CosineAnnealingLR
  T_max: 200
  eta_min: 0.0001

# 数据增强配置
augmentation:
  train:
    - random_crop:
        size: 32
        padding: 4
    - random_horizontal_flip:
        p: 0.5
    - random_rotation:
        degrees: 15
    - color_jitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
    - normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  
  test:
    - normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

# 日志配置
logging:
  log_dir: logs/cifar10_classification
  tensorboard: true
  wandb:
    enabled: false
    project: neurotrain-cifar
    entity: your_entity

# 检查点配置
checkpoint:
  save_dir: runs/cifar10_classification
  save_interval: 10
  keep_last_n: 5
  
# GPU配置
device:
  use_cuda: true
  device_ids: [0]  # GPU设备ID列表
  
# 随机种子
seed: 42

