# CIFAR-100图像分类配置文件

# 实验基本信息
name: cifar100_classification
description: CIFAR-100 image classification training

# 数据集配置
dataset:
  name: cifar100
  root_dir: data/cifar100
  config:
    download: true
    valid_ratio: 0.1  # 从训练集中划分10%作为验证集

# 数据加载配置
dataloader:
  batch_size: 128
  num_workers: 4
  pin_memory: true
  shuffle: true
  drop_last: false

# 模型配置
model:
  name: resnet50  # CIFAR-100类别更多，使用更大的模型
  num_classes: 100
  pretrained: false

# 训练配置
training:
  epochs: 300
  learning_rate: 0.1
  optimizer: sgd
  momentum: 0.9
  weight_decay: 0.0005
  scheduler: cosine
  warmup_epochs: 10
  
  # 损失函数
  loss: cross_entropy
  label_smoothing: 0.1  # 标签平滑，有助于提高泛化能力
  
  # 梯度裁剪
  grad_clip: 1.0
  
  # 混合精度训练
  use_amp: true

# 验证配置
validation:
  interval: 1  # 每个epoch验证一次
  metrics:
    - accuracy
    - top1_accuracy
    - top5_accuracy  # CIFAR-100可以使用top5准确率
    - precision
    - recall
    - f1_score

# 优化器配置
optimizer:
  type: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: true

# 学习率调度器配置
scheduler:
  type: CosineAnnealingLR
  T_max: 300
  eta_min: 0.0001

# 数据增强配置
augmentation:
  train:
    - random_crop:
        size: 32
        padding: 4
    - random_horizontal_flip:
        p: 0.5
    - random_rotation:
        degrees: 15
    - color_jitter:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.2
    - normalize:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
  
  test:
    - normalize:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]

# 日志配置
logging:
  log_dir: logs/cifar100_classification
  tensorboard: true
  wandb:
    enabled: false
    project: neurotrain-cifar
    entity: your_entity

# 检查点配置
checkpoint:
  save_dir: runs/cifar100_classification
  save_interval: 10
  keep_last_n: 5
  
# GPU配置
device:
  use_cuda: true
  device_ids: [0]  # GPU设备ID列表
  
# 随机种子
seed: 42

