# ImageNet-1K 数据集配置文件

dataset:
  name: imagenet  # 可选: imagenet, imagenet1k, imagenet-1k
  root_dir: data/imagenet  # ImageNet 数据集根目录
  
  config:
    return_path: false       # 是否返回图像路径
    class_to_idx_file: null  # 类别到索引映射文件（可选）
    
    # 数据增强配置（可选）
    # transform: ...
    # target_transform: ...

# 数据加载器配置
dataloader:
  batch_size: 256
  num_workers: 8
  shuffle: true
  pin_memory: true
  drop_last: true
  prefetch_factor: 2

# 训练配置
training:
  epochs: 90
  
  # 学习率调度
  optimizer:
    type: SGD
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 90
  
  # 损失函数
  loss:
    type: CrossEntropyLoss
    label_smoothing: 0.1
    
  # 评估指标
  metrics:
    - top1_accuracy  # Top-1 准确率
    - top5_accuracy  # Top-5 准确率
    - loss           # 损失值

# 数据预处理
preprocessing:
  # 训练集数据增强
  train:
    - RandomResizedCrop:
        size: 224
        scale: [0.08, 1.0]
        ratio: [0.75, 1.333]
    - RandomHorizontalFlip:
        p: 0.5
    - ColorJitter:
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
    - ToTensor: {}
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  
  # 验证集数据处理
  val:
    - Resize:
        size: 256
    - CenterCrop:
        size: 224
    - ToTensor: {}
    - Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

# 数据集元信息
# - 类别数: 1000
# - 训练集大小: 1,281,167 张图像
# - 验证集大小: 50,000 张图像
# - 测试集大小: 100,000 张图像
# - 任务类型: classification
# - 图像尺寸: 224x224 (ResNet等), 299x299 (Inception等)

