drive:
  classes: ["Retina"]
  train:
    source: "images/*.png"
    target: "1st_manual/*.png"
  test:
    source: "images/*.png"
    target: "1st_manual/*.png"
stare:
  classes: ["Retina"]
  train:
    source: "images/*.png"
    target: "1st_labels_ah/*.png"
  test:
    source: "images/*.png"
    target: "1st_labels_ah/*.png"
chasedb1:
  classes: ["Retina"]
  train:
    source: "images/*.png"
    target: "1st_manual/*.png"
  test:
    source: "images/*.png"
    target: "1st_manual/*.png"
