# DDP快速测试配置文件
# 用于快速验证DDP功能

output_dir = "./runs"
task = "DDP_Quick_Test"
entity = "Lab"
run_id = ""
device = "cuda"
seed = 42
classes = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
metrics = ['accuracy']
postprocess = "classification"

# DDP配置
[ddp]
enabled = true
log_level = "INFO"

[model]
name = "torchvision"
continue_checkpoint = ""
continue_ext_checkpoint = ""
pretrained = ""

[model.config]
arch = "resnet18"
n_channels = 1
n_classes = 10
input_sizes = [
    [1, 1, 224, 224]
]
dtypes = ["float32"]
pretrained = true

[[criterion]]
type = 'cross_entropy'
weight = 1.0
config = {}

[transform]
RESIZE = [224, 224]
HFLIP = [0.5]
PIL_TO_TENSOR = []
CONVERT_IMAGE_DTYPE = ['float32']

[dataset]
name = "MNIST"
base_dir = "./data/mnist"
betweens = {train = [0.0, 1.0], valid = [0.0, 1.0], test = [0.0, 1.0]}
config = {download = true}
ref = "mnist.yaml"

[dataloader]
num_workers = 2
shuffle = true
pin_memory = true

[train]
batch_size = 32
epoch = 5
save_period = 0.2
save_recovery_period = 0.2
grad_accumulation_steps = 0

[train.optimizer]
type = 'adam'
learning_rate = 1e-3
weight_decay = 1e-4

[train.scaler]
compute_type = 'float16'

[test]
batch_size = 32

[predict]
input = "data/mnist/test"

[predict.config]

[private]
wandb = false
mode = 0

[private.log]
verbose = true
debug = false
log_file_format = '%Y-%m-%d %H_%M_%S'
log_format = '%(asctime)s %(levelname)s | %(name)s | %(message)s'

[output]
save_best = true
save_last = true
save_interval = 1
