# DDP图像分割训练配置文件
# 用于医学图像分割的分布式训练

output_dir = "./runs"
task = "DDP_Segmentation"
entity = "Lab"
run_id = "" # 由程序随机设置
device = "cuda"
seed = 42
classes = ["background", "foreground"] # 二分类分割
metrics = ['iou', 'dice', 'accuracy', 'precision', 'recall', 'f1']
postprocess = "binary_segmentation"

# DDP配置
[ddp]
enabled = true
log_level = "INFO"

[model]
name = "unet"  # 使用UNet进行图像分割
continue_checkpoint = ""
continue_ext_checkpoint = ""
pretrained = ""

[model.config]
n_channels = 1         # 灰度图像
n_classes = 1          # 二分类
input_sizes = [
    [1, 1, 512, 512]   # 医学图像常用尺寸
]
dtypes = ["float32"]
bilinear = true        # UNet上采样方式

# 多损失函数配置
[[criterion]]
type = 'dice'
weight = 1.0
config = {}

[[criterion]]
type = 'bce'
weight = 0.5
config = {}

# 数据增强配置
[transform]
RESIZE = [512, 512]
HFLIP = [0.5]
VFLIP = [0.5]
ROTATION = [15]
INVERT = [0.1]         # 图像反转
PIL_TO_TENSOR = []
CONVERT_IMAGE_DTYPE = ['float32']

# 数据集配置
[dataset]
name = "MedicalDataset"
root_dir = "./data/medical"
config = {}
ref = "medical.yaml"

# 数据分割
[dataset.split]
type = "train_valid_test_split"
train = 0.7
valid = 0.15
test = 0.15
shuffle = true
random_state = 42

# 数据加载器
[dataloader]
num_workers = 4
shuffle = true
pin_memory = true
drop_last = true

# 训练配置
[train]
batch_size = 8         # 分割任务通常使用较小的批次
epoch = 200
save_period = 0.1
save_recovery_period = 0.1
grad_accumulation_steps = 2  # 使用梯度累积增加有效批次大小

# 优化器
[train.optimizer]
type = 'adam'
learning_rate = 1e-4
weight_decay = 1e-5

# 学习率调度
[train.lr_scheduler]
type = 'step'
warmup = 20
warmup_lr = 1e-5
update_policy = 'epoch'

# 混合精度
[train.scaler]
compute_type = 'float16'

# 早停
[train.early_stopping]
patience = 15
min_delta = 0.001

# 测试
[test]
batch_size = 8

# 预测
[predict]
input = "data/test/images"

[predict.config]
output_format = "numpy"
save_images = true
threshold = 0.5

# 私有配置
[private]
wandb = true
mode = 0

[private.log]
verbose = true
debug = false
log_file_format = '%Y-%m-%d %H_%M_%S'
log_format = '%(asctime)s %(levelname)s | %(name)s | %(message)s'

# 输出配置
[output]
save_best = true
save_last = true
save_interval = 20
