output_dir = "./output"
task = "TestModel"
entity = "Lab"
run_id = "" # be Random set by program
device = "cuda"
seed = 42
classes = ["Retina"]

[model]
name = "simple-net"
continue_checkpoint = ""
continue_ext_checkpoint = ""

[model.config]
n_channels = 1
n_classes = 1

[train]
batch_size = 1
epoch = 3
save_every_n_epoch = 1

[train.dataset]
name = "DRIVE"
path = "./data/DRIVE"
num_workers = 4

[train.augment_boost]
enabled = true
# (RESIZE, resize)
# (ROTATION, degree)
# (HFLIP, p)
# (VFLOP, p)
# (INVERT, p)
# (TO_TENSOR)
# (PIL_TO_TENSOR)
# (NORMALIZE, is_rgb)
config = {"ROTATION"=[10], "HFLIP"=[10], "VFLIP"=[10], "PIL_TO_TENSOR"=[]} 

[train.optimizer]
learning_rate = 3e-6
weight_decay = 1e-8
eps = 1e-8

[train.lr_scheduler]
enabled = false
warmup = 50
warmup_lr = 0.03

[train.scaler]
enabled = false
compute_type = 'bfloat16'

[train.early_stopping]
enabled = false
patience = 3

[test]
batch_size = 1

[test.dataset]
name = "DRIVE"
path = "./data/DRIVE"
num_workers = 4

[predict]
input = "data/DRIVE/test/images"

[predict.config]

[private]
wandb = false
log = true
verbose = false # info mode
debug = false # debug mode
mode = 0
log_file_format = '%Y-%m-%d %H_%M_%S'
log_format = '%(asctime)s %(levelname)s | %(name)s | %(message)s'