output_dir = "./output"
task = "TestModel"
entity = "Lab"
run_id = "0"
device = "cuda"
seed = 42
classes = ["Retina"]

[model]
name = "unet"
continue_checkpoint = ""

[model.config]
n_channels = 1
n_classes = 1

[train]
batch_size = 1
epoch = 40
save_every_n_epoch = 0

[train.dataset]
name = "CHASEDB1"
path = "./data/CHASEDB1"
num_workers = 0

[train.augment_boost]
enabled = true
config = {}

[train.optimizer]
learning_rate = 3e-6
weight_decay = 1e-8
eps = 1e-8

[train.lr_scheduler]
enabled = false
warmup = 50
warmup_lr = 0.03

[train.scaler]
enabled = false
compute_type = 'bfloat16'

[train.early_stopping]
enabled = false
patience = 3

[test]
batch_size = 1

[test.dataset]
name = "CHASEDB1"
path = "./data/CHASEDB1"
num_workers = 0

[predict]
input = "data/CHASEDB1/test/images"
config = {}

[private]
wandb = false
log = true
verbose = false
mode = 0